[project]
name = "heatpro"
version = "0.1.5"
description = "Generate heat demand load profile for distict heating"
authors = [
    { name = "Robinson Beaucour", email = "robinson.beaucour@cea.fr" },
    { name = "Nicolas Lamaison", email = "nicolas.lamaison@cea.fr" },
    { name = "Thibaut Wissocq", email = "thibaut.wissocq@cea.fr" },
]
requires-python = "~=3.9"
readme = "README.md"
license = "CeCILL-B"
dependencies = [
    "pandas>=2.1.0,<3",
    "matplotlib==3.9.0",
]

[dependency-groups]
dev = [
    "pytest>=8.1.1,<9",
    "pytest-cov>=5.0.0,<6",
    "nbmake>=1.5.4,<2",
]
doc = [
    "sphinx>=7.2.6,<8",
    "sphinx-rtd-theme>=2.0.0,<3",
    "recommonmark>=0.7.1,<0.8",
]
notebook = [
    "ipykernel>=6.29.4,<7",
    "plotly>=5.20.0,<6",
    "nbformat>=5.10.4,<6",
    "nbconvert>=7.16.4,<8",
]

[tool.uv]
default-groups = [
    "dev",
    "doc",
    "notebook",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
