[project]
name = "heatpro"
version = "0.2.1"
description = "Generate heat demand load profile for distict heating"
authors = [
    { name = "Robinson Beaucour", email = "robinson.beaucour@cea.fr" },
    { name = "Nicolas Lamaison", email = "nicolas.lamaison@cea.fr" },
    { name = "Thibaut Wissocq", email = "thibaut.wissocq@cea.fr" },
]
requires-python = ">=3.10"
readme = "README.md"
license = "CECILL-B"
dependencies = [
    "pandas>=2.3.3",
    "plotly>=6.5.2",
]

[dependency-groups]
cli = [
    "click>=8.3.3",
    "plotly>=6.5.2",
    "rich>=15.0.0",
]
dev = [
    "nbmake>=1.5.5",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "ruff>=0.15.2",
]
doc = [
    "recommonmark>=0.7.1",
    "sphinx>=8.1.3",
    "sphinx-rtd-theme>=3.1.0",
]
notebook = [
    "ipykernel>=7.2.0",
    "nbconvert>=7.17.0",
    "nbformat>=5.10.4",
    "plotly>=6.5.2",
]

[tool.setuptools]
include-package-data = true
package-dir = {"" = "."}

[tool.setuptools.package-data]
heatpro = [
    "./cold/needs_by_building_type_and_climatic_zone.json",
    "./cold/profile_full_week.csv",
    "./cold/profile_working_day.csv",
]

[tool.setuptools.packages.find]
where = ["."]

[tool.uv]
package = true

[tool.ruff]
line-length = 100

[project.scripts]
heatpro = "heatpro.cli:cli"
