name: build-test

on: [push, pull_request, workflow_dispatch]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10']
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Run tests
        run: uv run  --extra devpytest

      - name: Test notebooks
        run: uv run --extra dev --extra notebook pytest --nbmake ./notebooks/