name: documentations

on:
  push:
    branches:
      - public
  pull_request:
    branches:
      - public
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install poetry
          poetry lock
          poetry install --with doc
      - name: Sphinx build
        run: |
          poetry run sphinx-build -M html ./docs ./docs/_build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          force_orphan: true
